---
- name: Install mysql client and server
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=5000
  with_items:
    - mysql-client
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb
  notify:
    - restart mysql

- name: enable mysqld service
  action: service name=mysql state=started enabled=yes

- name: create my.cnf file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf backup=yes
  notify:
    - restart mysql

- name: MySQL | secure; check if root pw set
  fail: msg="Set the mysql root password to be used, set the mysql_root_password variable!"
  when: mysql_root_password is not defined

- name: Set mysql root password for localhost root account
  mysql_user: name=root host=localhost password={{mysql_root_password}}

- name: Copy .my.cnf file with root password credentials
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{item}} password={{mysql_root_password}}
  with_items:
    - '{{ ansible_hostname }}'
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{item}} state=absent
  with_items:
    - localhost
    - '{{ansible_hostname}}'
    - '{{ansible_fqdn}}'

- name: remove the test database
  mysql_db: name=test state=absent
